---
- name: Install rpi
  hosts: rpi
  become: true
  vars_files:
    - defaults/main.yml
    - defaults/secret.yml
  tasks:
    - include: tasks/main.yml
  roles:
    - role: ANXS.hostname
    - role: elboletaire.transmission
      become: true
      transmission_password: "{{ rpi_bt_passwd }}"
      transmission_rpc_auth_enabled: true
      transmission_rpc_whitelist_enabled: false
      transmission_download_dir: "{{ rpi_downloads }}"
      transmission_watch_dir_enabled: false
      transmission_watch_dir: "{{ rpi_downloads }}"
      transmission_rpc_auth_required: true
    - role: kodi
      become: true
      kodi_storage_group: "{{ rpi_storage_group }}"
