---
- name: Install rpi
  hosts: rpi
  become: true
  vars_files:
    - defaults/main.yml
    - defaults/secret.yml
  tasks:
    - include: tasks/main.yml
  roles:
    - role: ANXS.hostname
    - role: elboletaire.transmission
      become: true
      transmission_password: "{{ rpi_bt_passwd }}"
      transmission_rpc_auth_enabled: true
      transmission_rpc_whitelist_enabled: false
      transmission_download_dir: "{{ rpi_downloads }}"
      transmission_watch_dir_enabled: false
      transmission_watch_dir: "{{ rpi_downloads }}"
      transmission_rpc_auth_required: true
    - role: kodi
      become: true
      kodi_storage_group: "{{ rpi_storage_group }}"
      kodi_movies: "{{ rpi_movies }}" 
      kodi_music: "{{ rpi_series }}"
      kodi_pictures: "{{ rpi_pictures }}"
      kodi_series: "{{ rpi_downloads }}"
    - role: openvpnclient
      openvpn_remote_host: 'vpn.romcheg.me'
      openvpn_remote_port: 1195
      openvpn_dev: tap
      openvpn_keepalive: "10 3600"
      openvpn_ca_certificate: "{{ rpi_ovpn_ca_cert }}"
      openvpn_client_certificate: "{{ rpi_ovpn_client_cert }}"
      openvpn_client_key : "{{ rpi_ovpn_client_key }}"
      openvpn_client_pull: true
      openvpn_redirect_gateway: true
      openvpn_persist_key: true
      openvpn_persist_tun: true
      openvpn_comp_lzo: true
