---
- name: Create user group
  group:
    name: storageadmin
    state: present

- include: users.yml

- name: Create a mount point for the hdd
  file:
    path: /media/storage
    state: directory

- name: Add the external hdd to fstab
  mount:
    name: /media/storage
    src: /dev/disk/by-label/Storage
    fstype: xfs
    opts: "rw,relatime,attr2,inode64,noquota"
    state: mounted

- name: Grant permissions for downloads directory
  file:
    path: {{ downloads }}
    owner: debian-transmission
    group: storageadmin
    mode: "ug+rw"
    recurse: yes
    state: directory

- name: Grant permissions for music directory
  file:
    path: {{ music }}
    owner: kodi
    group: storageadmin
    mode: "ug+rw"
    recurse: yes
    state: directory

- name: Grant permissions for movies directory
  file:
    path: {{ movies }}
    owner: kodi
    group: storageadmin
    mode: "ug+rw"
    recurse: yes
    state: directory

- name: Grant permissions for photos directory
  file:
    path: {{ photos }}
    owner: kodi
    group: storageadmin
    mode: "ug+rw"
    recurse: yes
    state: directory

- name: Grant permissions for series directory
  file:
    path: {{ series }}
    owner: kodi
    group: storageadmin
    mode: "ug+rw"
    recurse: yes
    state: directory

- name: Generate EN locale
  locale_gen:
    name: en_US.UTF-8
    state: present

- name: Generate UK locale
  locale_gen:
    name: uk_UA.UTF-8
    state: present
