---
- name: Create user group
  group:
    name: "{{ rpi_storage_group }}"
    state: present

- name: Add romcheg user
  user:
    name: romcheg
    shell: /bin/bash
    groups: "{{ rpi_storage_group }},root"
    append: yes
    password: "{{ rpi_romcheg_password }}"
    state: present
