---
- name: Create user group
  group:
    name: "{{ rpi_storage_group }}"
    state: present

- name: Add romcheg user
  user:
    name: romcheg
    shell: /usr/bin/zsh
    groups: "{{ rpi_storage_group }},{{ rpi_sudo_group }}"
    append: yes
    password: "{{ rpi_romcheg_password }}"
    state: present

- name: Add local public key to authorized_keys
  authorized_key:
    user: "{{ item }}"
    key: "{{ rpi_public_key }}"
  with_items:
    - romcheg

- name: Install oh-my-zsh for romcheg
  become: true
  become_user: romcheg
  shell: curl -L https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh | sed -e '83,96d' | bash
