---
- name: Create user group
  group:
    name: "{{ storage_group }}"
    state: present

  # - name: Add kodi user
  #   user:
  #     name: kodi
  #     shell: /bin/bash
  #     groups: "storageadmin,root"
  #     append: yes
  #     password: "$6$rounds=656000$zsHZAd0Mli9LoAiO$ny6Fs.VIT5PxqFL4ZDwP2L8tua7zKzYgbB2w8RYY93QsB9XAE1Y4etktTh.IqZKqlDzWyleQfUQ7lUuH/kpyx0"
- name: Add romcheg user
  user:
    name: romcheg
    shell: /bin/bash
    groups: "{{ storage_group }},root"
    append: yes
    password: "{{ romcheg_password }}"
