---
# defaults file for openvpn

openvpn_client_pull: false
openvpn_dev: tun
openvpn_comp_lzo: true
openvpn_keepalive: '10 60'
openvpn_nobind: true
openvpn_persist_key: true
openvpn_persist_tun: true
openvpn_proto: udp
openvpn_redirect_gateway: false
openvpn_remote_host: ''
openvpn_remote_port: 1194
openvpn_remote_proto: "{{ openvpn_proto }}"
openvpn_status: openvpn-status.log
openvpn_verb: 3

openvpn_ca_certificate: ''
openvpn_client_certificate: ''
openvpn_client_key: ''
