---
# tasks file for openvpn

- name: Install OpenVPN packages
  become: yes
  apt:
    name: "{{ openvpn_package  }}"
    state: present
  tags:
    - openvpn

- name: Create OpenVPN client configuration file
  become: yes
  template:
    src: client.conf.j2
    dest: /etc/openvpn/client.conf
    owner: root
    group: root
    mode: 0640
  tags:
    - openvpn

- name: Ensure OpenVPN service is started and enabled on boot
  become: yes
  service:
    name: "{{ openvpn_service_name }}"
    state: reloaded
    enabled: yes
  tags:
    - openvpn
